use home;
select * from sales_transactions;
select * from sales;

#1.Find the total quantity sold for each product.
select product, 
sum(quantity) as `total quantity`
from sales_transactions 
group by Product;

#2.Calculate the total revenue (quantity * unit_price) generated by each product.
select product, 
round(sum(quantity * amount), 2) as `total revenue`
from sales_transactions 
group by product;

#3.List the total number of sales (transactions) per category.
select product, 
count(product) as total 
from sales_transactions 
group by product;

#4.Find the average unit price for each category.
select product, 
round(avg(amount), 2) as average 
from sales_transactions 
group by product; 

#5.Show the max, min, and average quantity sold per city.
select location, 
min(quantity) 'minimum quantity', 
max(quantity) 'max quantity', 
avg(quantity) 'average quantity' 
from sales_transactions 
group by location;

#6.Find the count and total sales revenue per city.
select location, 
count(quantity) 'count', 
sum(Quantity *  amount) as 'total revenue' 
from sales_transactions 
group by location;

#7.List each category and the total revenue generated from that category, ordered by highest revenue first.
select product, 
round(sum(quantity * amount), 2) `total revenue` 
from sales_transactions 
group by product 
order by product desc;

#8.Find the total quantity sold and average unit price per product where total quantity sold is more than 10.
select product, 
sum(quantity) `total quantity`, 
round(avg(amount), 2) `average amount` 
from sales_transactions 
group by product 
having sum(quantity) > 10;

#9.List the cities where the total sales revenue exceeds 10,000.
select location, 
sum(quantity * amount)  `total sales revenue` 
from sales_transactions 
group by location 
having sum(quantity * amount) > 10000;

#10.Find the product with the highest total revenue (quantity * unit_price).
select product, 
round(sum(quantity * amount), 2) `total revenue` 
from sales_transactions 
group by product 
order by `total revenue` desc limit 1; 

#11.List categories with average quantity sold less than 3.
select product, 
round(avg(quantity), 2) `average_quantity` 
from sales_transactions 
group by product 
having `average_quantity` < 3;

#12.Find total sales and count of transactions for each city and category combination.
select product, location,
round(sum(quantity * amount), 2) `total sales`, 
count(transactionID) `total trasactions` 
from sales_transactions 
group by location, product;

#13.List all products with the number of transactions and average revenue per transaction.
select product, 
count(transactionID) as `number of trasactions`, 
round(avg(quantity * amount), 2) `average revenue` 
from sales_transactions 
group by product;

#14.For each city, find the product sold the most (by total quantity). 
select location, product,
sum(quantity) `total quantity` 
from sales_transactions
group by location, product
order by `total quantity` desc;

#15.Find all categories where total revenue is not between 1,000 and 5,000.
select product, 
round(sum(quantity * amount), 2) `total revenue` 
from sales_transactions 
group by product 
having `total revenue` not between 1000 and 5000;

#16.Find the average unit price for each product only for those with more than 5 total transactions.
select product, count(transactionID) `count of transactions`, 
round(avg(amount), 2) as `average unit price` 
from sales_transactions 
group by product 
having `count of transactions` > 5;

#17.List each city and the number of unique customers who bought products there.
select location, product, 
count(distinct customername) `unique customers` 
from sales_transactions 
group by location, product;

#18.For each product, find the total quantity sold in cities starting with the letter ‘B’.
select location, product, 
sum(quantity) `total quantity` 
from sales_transactions 
group by product,location 
having location like "B%";

#19.List cities and their total revenue, but only for cities with more than 10 transactions. 
select location, 
round(sum(quantity * amount), 2) `total revenue`, 
count(transactionID) `transactions` 
from sales_transactions 
group by location 
having count(*) > 10;

#20.Find the products with average quantity sold per transaction greater than 2 and total revenue exceeding 3,000.
select product, 
round(avg(quantity), 2) `average quantity`,
round(sum(quantity * amount), 2) `total revenue` 
from sales_transactions 
group by product 
having `average quantity` > 2 and `total revenue` > 3000; 